version: '3.8'

services:
  portafolio-front:
    image: nginx:alpine
    container_name: portafolio-front
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
