version: '3.8'

services:
  portafolio-front:
    build: .
    container_name: portafolio-front
    restart: unless-stopped
    ports:
      - "80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
